# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'Travis Green'
email: 'contact@travisgreen.net'
description: > # this means to ignore newlines until "baseurl:"
  malware and musings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://travisgreen.net" # the base hostname & protocol for your site
twitter_username: travisbgreen
github_username:  travisbgreen
google_analytics: UA-66565917-1
linkedin_username: travisgreen

show_excerpts: true

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal