title: 'Travis Green'
email: 'contact@travisgreen.net'
#description: 
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://travisgreen.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: travisbgreen
github_username:  travisbgreen
google_analytics: UA-66565917-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME