title: 'Travis Green'
email: 'contact@travisgreen.net'
description: >
  malware and musings
baseurl: ""
url: "http://travisgreen.net"
twitter_username: travisbgreen
github_username:  travisbgreen
google_analytics: G-P149WPNRPD
linkedin_username: travisgreen
theme: jekyll-theme-minimal
