# Site settings
title: 'Travis Green'
email: 'contact@travisgreen.net'
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://travisgreen.net" # the base hostname & protocol for your site
twitter_username: travisbgreen
github_username:  travisbgreen

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
