# Site settings
title: Travis Green
email: contact@travisgreen.net
description: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://travisgreen.net" # the base hostname & protocol for your site
twitter_username: travisbgreen
github_username:  travisbgreen

# Build settings
markdown: kramdown
